name: Build SQL Database

description: Build a SQL Database with Flyway

inputs:
  db-server-name:
    description: The name of the database server to build the database on.
    required: true
  db-name:
    description: The name of the database to bubild.
    required: true
  additional-build-params:
    description: A string containing any additional build parameters that will be tacked on to the end of the powershell run command
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Database Dependencies
      shell: pwsh
      run: ${{ github.action_path }}/scripts/installpowershelldependencies.ps1

    - name: Build Database
      shell: pwsh
      run: ${{ github.action_path }}/scripts/build-flyway.ps1 -dbServerName "${{ inputs.db-server-name }}" -dbName "${{ inputs.db-name }}" ${{ inputs.additional-build-params }}