name: Build SQL Database

description: Build a SQL Database with Flyway

inputs:
  db-server-name:
    description: The name of the database server to build the database on.
    required: true
  db-name:
    description: The name of the database to bubild.
    required: true
  install-mock-db-objects:
    description: Specifies whether mock db objects should be used to fill out dependencies.
    default: false
  mock-db-object-nuget-feed-url:
    description: The url to the nuget feed containing the mock database objects. This should be set if the install-mock-db-objects flag is set.
  incremental:
    description: Specifies whether to drop and recreate the database before building, or apply to the current database.
    default: false
  run-tests:
    description: Specifies whether or not to run tests.
    default: false

runs:
  using: "composite"
  steps:
    - name: Install Database Dependencies
      shell: pwsh
      run: ${{ github.action_path }}/scripts/installpowershelldependencies.ps1

    - name: Build Database
      shell: pwsh
      run: |
        ${{ github.action_path }}/scripts/build-flyway.ps1 -dbServerName "${{ inputs.db-server-name }}" `
        -dbName "${{ inputs.db-name }}" -installMockDbObjects:$${{ inputs.install-mock-db-objects }} `
        -mockDbObjectNugetFeedUrl "${{ inputs.mock-db-object-nuget-feed-url }}" `
        -incremental:$${{ inputs.incremental }} -runTests:$${{ inputs.run-tests }}